#!/bin/bash

for i in $(ls /usr/lib/libpangoxft-*)
do
    new_link="$(echo "$i" | sed 's|libpangoxft|libpangox|g')"

    if [ ! -e "$new_link" ]; then
        ln -s "$i" "$new_link" 2> /dev/null
    fi

done
