#!/bin/bash

if ! getent group vboxusers > /dev/null; then
    groupadd vboxusers
fi

for USER_ADD in $(ls -1 /home); do
    if id "$USER_ADD" &>/dev/null; then
        gpasswd -a "$USER_ADD" vboxusers
    fi
done

vboxreload