#!/bin/bash

# list all normal users
users=$(eval getent passwd {$(awk '/^UID_MIN/ {print $2}' /etc/login.defs)..$(awk '/^UID_MAX/ {print $2}' /etc/login.defs)} | cut -d: -f1)

for user in ${users[@]}; do
    if [ -n "$(grep amdgpu.ppfeaturemask /etc/default/grub)" ];then
        sed -i '/GRUB_CMDLINE_LINUX_DEFAULT/s/ amdgpu.ppfeaturemask=0xfffd7fff//' /etc/default/grub
        update-grub
    fi
    rm /home/$user/.config/autostart/org.corectrl.CoreCtrl.desktop
    rm /home/$user/.config/corectrl/corectrl.ini
    rm /etc/polkit-1/rules.d/90-corectrl-$user.rules
done
