#!/bin/bash

if getent group vboxusers > /dev/null; then
    for USER in $(getent group vboxusers | cut -d: -f4 | tr ',' ' '); do
        gpasswd -d "$USER" vboxusers
    done
    groupdel vboxusers
fi

rmmod vboxnetflt vboxnetadp vboxdrv